AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Pinpoint Stock Bot - responds to a text message from a user with current
  stock price. Incoming text message must conform to the format "$<<stockname>>",
  or it will be ignored.

  '
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Pinpoint-Stock-Bot
    Description: This application responds to an incoming SMS (with format 'stock
      stocksymbol') with current stock information.
    Author: Brooke Mitchell
Parameters:
  APIkey:
    Type: String
    Default: APIkey
    Description: (Required) OpenWeatherMap API key
    AllowedPattern: ^[A-Za-z0-9-]+$
    ConstraintDescription: Required parameter.
  ApplicationId:
    Type: String
    Default: PinpointApplicationId
    Description: (Required) Pinpoint application ID (project ID)
    AllowedPattern: ^[A-Za-z0-9-]+$
    ConstraintDescription: Required parameter.
Globals:
  Function:
    Timeout: 10
Resources:
  smsResponderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverless-stock-bot/aee5c4deb488cead48f3b283a85b9dec
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          ApplicationId:
            Ref: ApplicationId
          APIkey:
            Ref: APIkey
      Policies:
      - Statement:
        - Sid: PinpointAccess
          Effect: Allow
          Action:
          - mobiletargeting:*
          Resource: '*'
        - Sid: PinpointSNStopic
          Effect: Allow
          Action:
          - sns:*
          Resource:
            Ref: smsResponderIncomingSNSTopic
      Events:
        incomingSNS:
          Type: SNS
          Properties:
            Topic:
              Ref: smsResponderIncomingSNSTopic
  smsResponderIncomingSNSTopic:
    Type: AWS::SNS::Topic
Outputs:
  smsResponderFunction:
    Description: Lambda Function ARN
    Value:
      Fn::GetAtt:
      - smsResponderFunction
      - Arn
  smsResponderFunctionIamRole:
    Description: Implicit IAM Role created for function
    Value:
      Fn::GetAtt:
      - smsResponderFunctionRole
      - Arn
